function OCVModel_dSOC = OCVModel_dSOC(in1,SOC)
%OCVModel_dSOC
%    OCVModel_dSOC = OCVModel_dSOC(IN1,SOC)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    31-Oct-2025 12:00:55

p2 = in1(:,2);
p3 = in1(:,3);
p4 = in1(:,4);
p5 = in1(:,5);
p6 = in1(:,6);
p7 = in1(:,7);
OCVModel_dSOC = p2+SOC.*p3.*2.0+SOC.^2.*p4.*3.0+SOC.^3.*p5.*4.0+SOC.^4.*p6.*5.0+SOC.^5.*p7.*6.0;
end
