function OCVModel = OCVModel(in1,SOC)
%OCVModel
%    OCVModel = OCVModel(IN1,SOC)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    06-Nov-2025 21:37:01

p1 = in1(:,1);
p2 = in1(:,2);
p3 = in1(:,3);
p4 = in1(:,4);
p5 = in1(:,5);
p6 = in1(:,6);
p7 = in1(:,7);
OCVModel = p1+SOC.*p2+SOC.^2.*p3+SOC.^3.*p4+SOC.^4.*p5+SOC.^5.*p6+SOC.^6.*p7;
end
