function ocv_func = OCVModel_Fmin(x1)
%OCVModel_Fmin
%    OCV_FUNC = OCVModel_Fmin(X1)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    21-Nov-2025 15:51:28

et1 = x1.*4.91430673651004-x1.^2.*3.336887401816988e+1+x1.^3.*1.329761341291414e+2-x1.^4.*2.957690855425855e+2+x1.^5.*3.835997964535939e+2;
et2 = x1.^6.*(-2.890652863803284e+2)+3.19642416797593;
ocv_func = et1+et2;
end
