function ocv_func = OCVModel_Fmin(x1)
%OCVModel_Fmin
%    OCV_FUNC = OCVModel_Fmin(X1)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    30-Nov-2025 23:29:55

et1 = x1.*1.480650010586774e+1-x1.^2.*9.172799810114347e+1+x1.^3.*2.864360729419029e+2-x1.^4.*4.410459790352386e+2+x1.^5.*2.482899026342759e+2;
et2 = x1.^6.*1.497319388784275e+2-x1.^7.*2.551137652500233e+2+x1.^8.*9.016278286442224e+1+2.567692990252117;
ocv_func = et1+et2;
end
