function ocv_func = OCVModel_Fmin(x1)
%OCVModel_Fmin
%    OCV_FUNC = OCVModel_Fmin(X1)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    21-Nov-2025 15:18:43

et1 = x1.*5.503096773384061-x1.^2.*3.904195614768297e+1+x1.^3.*1.522327106903016e+2-x1.^4.*3.138652229783785e+2+x1.^5.*3.46060330735088e+2;
et2 = x1.^6.*(-1.852590759453203e+2)+3.1951272803121;
ocv_func = et1+et2;
end
