function [fitresult, gof] = createFit(Q, V)
%CREATEFIT(Q,V)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: Q from Discharge01C
%      Y Output: V from Discharge01C
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 14-Feb-2026 19:04:42


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( Q, V );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );
opts = fitoptions( 'Method', 'SmoothingSpline' );
opts.SmoothingParam = 5.33108816248844e-05;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'V vs. Q', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'Q', 'Interpreter', 'none' );
ylabel( 'V', 'Interpreter', 'none' );
grid on


