function [fitresult, gof] = createFit1(SoC, V)
%CREATEFIT1(SOC,V)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: SoC from Discharge01CV2
%      Y Output: V from Discharge01CV2
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 14-Feb-2026 20:13:11


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( SoC, V );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );
opts = fitoptions( 'Method', 'SmoothingSpline' );
opts.SmoothingParam = 0.99999993492952;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'V vs. SoC', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'SoC', 'Interpreter', 'none' );
ylabel( 'V', 'Interpreter', 'none' );
grid on


