function R0Model = R0Model(in1,SOC,current)
%R0Model
%    R0Model = R0Model(IN1,SOC,CURRENT)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    31-Oct-2025 12:00:55

p8 = in1(:,8);
p9 = in1(:,9);
p10 = in1(:,10);
p11 = in1(:,11);
R0Model = p8+SOC.*p9+current.*p11+SOC.^2.*p10;
end
